config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: 'auth', controllers: { registrations: :custom_registrations }, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :contacts do
    get 'autocomplete', on: :collection
  end

  post '/groups', to: 'groups#create'

  get '/dashboard', to: 'dashboard#index'

  get 'dashboard/index'

  get 'home/index'

  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  belongs_to :group
  belongs_to :user

  # paginates_per (5)

  validates :name, :email, :group_id, presence: true
  validates :name, length: { minimum: 2 }

  has_attached_file :avatar, styles: { medium: '150x150>', thumb: '100x100>' }, default_url: '/images/:style/default.png'
  validates_attachment_content_type :avatar, content_type: %r{\Aimage/.*\z}

  def gravatar
    hash = Digest::MD5.hexdigest(email.downcase)
    "https://www.gravatar.com/avatar/#{hash}"
  end

  scope :search, -> (term) do
    where('LOWER(name) LIKE :term or LOWER(company) LIKE :term or LOWER(email) LIKE :term', term: "%#{term.downcase}%") if term.present?
  end

  # def self.search(term)
  #   if term && !term.empty?
  #     where('name LIKE ?', "%#{term}%")
  #   else
  #     all
  #   end
  # end

  scope :by_group, -> (group_id) { where(group_id: group_id) if group_id.present? }

  # def self.by_group(group_id)
  #   if group_id && !group_id.empty?
  #     where(group_id: group_id)
  #   else
  #     all
  #   end
  # end

end # class

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_many :contacts
  belongs_to :user

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contacts
  has_many :groups


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :show_404


  def after_sign_in_path_for(resource)
     stored_location_for(resource) || dashboard_path
  end

  def after_sign_up_path_for(resource)
      after_sign_in_path_for(resource)
  end


  private

  def user_not_authorized
    flash[:danger] = "You are not authorized to perform this action."
    redirect_to action: :index
  end

  def show_404
    render template: "errors/404", status: 404
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end#class

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_contact, only: %i[edit update destroy]

  def index
    session[:selected_group_id] = params[:group_id]
    @contacts = current_user.contacts.by_group(params[:group_id]).search(params[:term]).order(created_at: :desc).page(params[:page])
  end

  def autocomplete
    @contacts = current_user.contacts.search(params[:term]).order(created_at: :desc).page(params[:page])
    render json: @contacts.map { |contact| { id: contact.id, value: contact.name } }
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      flash[:success] = 'Contact Saved'
      redirect_to contacts_path(previous_query_string)
    else
      flash[:error] = 'Contact could not be created'
      render 'new'
    end
  end

  def show
    @contacts = Contact.find_contact
  end


  def edit
    authorize @contact
  end

  def update
    authorize @contact
    if @contact.update(contact_params)
      flash[:success] = 'Contact was successfully updated'
      redirect_to contacts_path(previous_query_string)
    else
      flash[:error] = 'Contact could not be updated'
      render 'edit'
    end
  end

  def destroy
    authorize @contact
    @contact.destroy
    flash[:success] = 'Contact was successfully deleted'
    redirect_to contacts_path
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :company, :phone, :group_id, :avatar)
  end

  def find_contact
    @contact = Contact.find(params[:id])
  end

  def previous_query_string
    session[:selected_group_id] ? { group_id: session[:selected_group_id] } : {}
  end
end # class

app/controllers/custom_registrations_controller.rb
class CustomRegistrationsController < Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
    dashboard_path
  end

end#class

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
  
end#class

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      render json: @group, status: :created
    else
      render json: @group.errors.full_messages, status: :unprocessable_entity
    end
  end



private

def group_params
  params.require(:group).permit(:name)
end

end#class

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active_item(uri)
    uri_segments = request.fullpath.split(/\/|\?/)
    uri_segments[1] === uri ? 'active' : ''
  end

  def has_error?(resource,field)
    resource.errors.messages[field].present?
  end

  def get_error(resource, field)
    resource.errors.messages[field].join(', ')
  end

end

app/helpers/contacts_helper.rb
# frozen_string_literal: true

module ContactsHelper
end

app/helpers/custom_registrations_helper.rb
module CustomRegistrationsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<tr>
  <td class="middle">
    <div class="media">
      <div class="media-left">
        <a href="#">
          <%= image_tag contact.avatar.present? ? contact.avatar.url(:thumb) : contact.gravatar, class: "media-object", style: "width:100px; height; 100px" %>
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= contact.name %></h4>
        <address>
          <strong><%= contact.company %></strong><br>
          <%= contact.email %>
        </address>
      </div>
    </div>
  </td>
  <td width="100" class="middle">
    <div>
      <%= link_to edit_contact_path(contact), class:"btn btn-circle btn-default btn-xs", title: "Edit" do %>
      <i class="glyphicon glyphicon-edit"></i>
    <% end %>
    <%= link_to contact_path(contact), method: :delete, class:"btn btn-circle btn-danger btn-xs", title: "Delete", data: {confirm: "Are you sure?"} do %>
    <i class="glyphicon glyphicon-remove"></i>
  <% end %>
</div>
</td>
</tr>

app/views/contacts/_form.html.erb
<%= form_for(@contact, html: { multipart: true }) do |f| %>

<div class="panel-body"> 
  <div class="form-horizontal">
    <div class="row">
      <div class="col-md-8">

        <%= content_tag :div, class: "form-group #{ 'has-error' if has_error?(@contact, :name) }" do %>
          <%= f.label :name, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :name, class: "form-control" %>
            <% if has_error?(@contact, :name) %>
            <span class="help-block">
               <%= get_error(@contact, :name) %>
            </span>
            <% end %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :company, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :company, class: "form-control" %>
          </div>
        </div>

        <%= content_tag :div, class: "form-group #{ 'has-error' if has_error?(@contact, :email) }" do %>
          <%= f.label :email, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :name, class: "form-control" %>
            <% if has_error?(@contact, :email) %>
            <span class="help-block">
               <%= get_error(@contact, :email) %>
            </span>
            <% end %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :phone, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_field :phone, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :address, class: "control-label col-md-3" %>
          <div class="col-md-8">
            <%= f.text_area :address, class: "form-control", rows: 3 %>
          </div>
        </div>

        <%= content_tag :div, class: "form-group #{ 'has-error' if has_error?(@contact, :group_id) }" do %>
          <%= f.label :group_id, class: "control-label col-md-3" %>
          <div class="col-md-5">
             <% attr = { prompt: "Select Group" } %>
             <% attr[:selected] = session[:selected_group_id].to_i if session[:selected_group_id] %>
             <%= f.collection_select :group_id, current_user.groups, :id, :name, attr, class: "form-control" %>
          </div>
          <div class="col-md-3">
              <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
          </div>
           </div>
           <% if has_error?(@contact, :group_id) %>
              <div class="form-group">
                  <div class="col-md-offset-3 col-md-8">
                      <span class="help-block">
                          <%= get_error(@contact, :group_id) %>
                      </span>
                  </div>
              </div>
            <% end %>
           <% end %>
            <div class="form-group" id="add-new-group">
              <div class="col-md-offset-3 col-md-8">
                <div class="input-group">
                  <input type="text" name="new_group" id="new_group" class="form-control">
                  <span class="input-group-btn">
                    <a id="save-group-btn" class="btn btn-default">
                      <i class="glyphicon glyphicon-ok"></i>
                    </a>
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
                <%= image_tag @contact.avatar.url(:medium) %>
              </div>
              <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
              <div class="text-center">
                <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <%= f.submit @contact.new_record? ? "Save" : "Update", class: "btn btn-primary" %>
              <a href="#" class="btn btn-default">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/contacts/edit.html.erb
<div class="col-md-offset-2 col-md-8">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>Edit Contact</strong>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="col-md-3">
  <%= render 'layouts/sidebar' %>
</div>

<div class="col-md-9">

<div class="panel panel-default">
  <div class="panel-heading clearfix">
      <div class="pull-left">
          <h4>All Contacts</h4>
      </div>
    <div class="pull-right">
        <%= link_to new_contact_path, class: "btn btn-success" do %>
           <i class="glyphicon glyphicon-plus"></i>
           Add Contact
        <% end %>
    </div>
  </div>

  <table class="table">
     <%= render @contacts %>
  </table>

<% if @contacts.blank? %>
  <div class="panel-footer message">
    <div class="alert alert-warning">
      <strong>Contact not found</strong>
    </div>
  </div>
 <% end %>
</div>

    <div class="text-center">
        <%= paginate @contacts %>
    </div>
</div>

app/views/contacts/new.html.erb
<div class="col-md-offset-2 col-md-8">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>Add Contact</strong>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="col-md-10 col-md-offset-1">
    <div class="jumbotron text-center">
        <h2><%= current_user.name %></h2>
        <p class="lead">See your progress:</p>
        <h4> 30 leads added this month! </h4>
        <h5> John added 10 leads this month!</h5>
        <h5> Casey added 3 leads this month! </h5>
        <p>
          <%= link_to "Manage Leads", contacts_path, class: "btn btn-default" %>
        </p>
    </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>

<%= link_to "Manage Leads", contacts_path, class: "btn btn-default btn-lg" %>
<% else %>

<div class="col-md-10 col-md-offset-1">
    <div class="jumbotron text-center">
        <h3>Free Online Lead Manager for Real Estate Agents</h3>
        <p class="lead">Organize your leads freely and easily with ListMe</p>
    </div>
</div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
    <script>
      <% flash.each do |type, message| %>
      <% type = type.to_s.gsub('alert', 'error').gsub('notice', 'info') %>
       toastr["<%= type %>"]("<%= message %>", "<%= type.upcase %>");
      <% end %>
    </script>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |type,message| %>
  <%= content_tag :div, message, class: "alert alert-#{type}" %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "ListMe", root_path, class: "navbar-brand text-uppercase" %>
    </div>
    <!-- /.navbar-header -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <% if !user_signed_in? %>
        <div class="navbar-right">
          <%= link_to "Login", new_user_session_path, class: "btn btn-default navbar-btn" %>
          <%= link_to "Register", new_user_registration_path, class: "btn btn-primary navbar-btn" %>
        </div>
      <% else %>

        <ul class="nav navbar-nav">
          <li class="<%= active_item('dashboard')%>"><%= link_to "Dashboard", dashboard_path %></li>
          <li class="<%= active_item('contacts')%>"><%= link_to "All Contacts", contacts_path %></li>
        </ul>

        <ul class="nav navbar-right navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <i class="glyphicon glyphicon-user"></i>
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li>
                <%= link_to "Profile", edit_user_registration_path %>
              </li>
              <li>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        </ul>
        <%= render 'layouts/search_form' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_search_form.html.erb
<%= form_tag(contacts_path, class: "navbar-form navbar-right", role: "search", method: :get) do %>
   <div class="input-group">
     <%= text_field_tag :term, params[:term], class: "form-control", placeholder: "Search...", autocomplete: "off" %>
     <%= hidden_field_tag :group_id, params[:group_id] %>
     <span class="input-group-btn">
       <button class="btn btn-default" type="submit">
           <i class="glyphicon glyphicon-search"></i>
       </button>
     </span>
    </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="list-group">
  <% active = (params[:group_id] == nil || params[:group_id].empty?) && !session[:selected_group_id] ? 'active' : '' %>
    <%= link_to contacts_path, class: "list-group-item #{active}" do %>
    All Contacts
    <span class="badge"><%= current_user.contacts.count %></span>
  <% end %>

  <% current_user.groups.each do |group| %>
    <% active = params[:group_id].to_i == group.id || (session[:selected_group_id] && session[:selected_group_id].to_i == group.id) ? 'active' : '' %>
      <%= link_to contacts_path(group_id: group.id), class: "list-group-item #{active}" do %>
      <%= group.name %> <span class="badge"><%= group.contacts.count %></span>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ListMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>

    <!-- content -->
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>